services:
  symfony-app:
    build:
      context: ./api_majama
      dockerfile: Dockerfile
    container_name: symfony-app
    ports:
      - "8000:8000"
    volumes:
      - ./api_majama:/var/www/html
    environment:
      - DATABASE_URL=mysql://Kwett:admin@mysql-db:3306/Majama
      - APP_ENV=prod
      - APP_DEBUG=0
      - GOOGLE_MAPS_API_KEY=AIzaSyBPoKn_fYWJkfbv6rY9OdboGlgJ7Nd1wcc
    depends_on:
      - mysql-db
    networks:
      - majama-network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Majama
      MYSQL_USER: Kwett
      MYSQL_PASSWORD: admin
      TZ: 'UTC'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - majama-network

  angular-app:
    build:
      context: ./front_majama
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front_majama/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - symfony-app
    networks:
      - majama-network

volumes:
  mysql-db:

networks:
  majama-network:
